' Gambas module file

'recorrer directorio y devolver contenido de fichero similar unido

Public Function recorrer(ruta As String, contenido As String[]) As String

  Dim archivo As String

  For Each archivo In Dir(ruta).Sort()

    If IsDir(ruta & "/" & archivo) Then
      Print "Directorio: " & ruta & "/" & archivo
      recorrer(ruta & "/" & archivo, contenido)
    Else
      'solo añadir ficheros new.csv
      If InStr(archivo, ".new.csv") <> 0 Then
        Print "fichero: " & ruta & "/" & archivo
        'fichero similar al solicitoado
        contenido[0] &= ruta & "/" & archivo & gb.Lf
      Endif

    Endif

  Next

End
